name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código
        uses: actions/checkout@v4
      
      - name: Setup Python Test
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
          pip install flake8 pytest
      
      - name: Rodar lint com flake8
        run: |
          flake8 src/
      
      - name: Rodar testes
        run: PYTHONPATH=src pytest src/tests
      
      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Docker Login
        uses: docker/login-action@v3.5.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t test-image -f docker/conversor/Dockerfile .

      - name: Testar container
        run: |
          docker run --rm test-image python app.py --help

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: docker/conversor/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/conversor-web:latest
            ${{ secrets.DOCKER_USERNAME }}/conversor-web:${{ github.sha }}

  deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Deploy to EC2
          uses: appleboy/ssh-action@v0.1.6
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USER  }}
            key: ${{ secrets.EC2_KEY  }}
            script: |
              docker stop conversor-web || true
              docker rm conversor-web || true
              docker pull ${{ secrets.DOCKER_USERNAME }}/conversor-web:latest
              docker run -d --name conversor-web -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/conversor-web:latest


          
          



