name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código
        uses: actions/checkout@v4
      
      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1
      
      - name: Build the Docker image
        run: docker build -t conversor-web:latest -f docker/conversor/Dockerfile .
      
      - name: Docker Login
        uses: docker/login-action@v3.5.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}



